name: social_media_recorder
description: A Flutter package for both android and iOS which provides  Audio recorder from microphone to a given file path through Button to record voice like social media Button
version: 1.0.0
homepage: https://github.com/SunnatilloShavkatov/social_media_recorder.git

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.2
  path_provider: ^2.1.2
  provider: ^6.1.2
  record: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/